// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfip8z_y0AUb2q-anFERV4QzTk54bulYI',
    appId: '1:667371289794:web:01ff7f2672c70dc610cf5b',
    messagingSenderId: '667371289794',
    projectId: 'just-split-62b39',
    authDomain: 'just-split-62b39.firebaseapp.com',
    storageBucket: 'just-split-62b39.firebasestorage.app',
    measurementId: 'G-SYVNW60FKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vYsJRO0MQKfgLc8_uLPQJT_xYoMre_A',
    appId: '1:667371289794:android:3c5ad6c2d024669410cf5b',
    messagingSenderId: '667371289794',
    projectId: 'just-split-62b39',
    storageBucket: 'just-split-62b39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2gdPVfOwu2bpw9wXmikXdaVft6Uz2Vw',
    appId: '1:667371289794:ios:1419fe8cf3586bf910cf5b',
    messagingSenderId: '667371289794',
    projectId: 'just-split-62b39',
    storageBucket: 'just-split-62b39.firebasestorage.app',
    androidClientId: '667371289794-hf34tiihtnmbt7q4sblcdpvetjvu1msv.apps.googleusercontent.com',
    iosClientId: '667371289794-gpldboqhguh4slimh6dnfhg55p4fvsrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.justSplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfip8z_y0AUb2q-anFERV4QzTk54bulYI',
    appId: '1:667371289794:web:504f238f16e193c410cf5b',
    messagingSenderId: '667371289794',
    projectId: 'just-split-62b39',
    authDomain: 'just-split-62b39.firebaseapp.com',
    storageBucket: 'just-split-62b39.firebasestorage.app',
    measurementId: 'G-2R35KPMPV6',
  );
}
